org.gradle.jvmargs=-Xmx4G -XX:+UseParallelGC
org.gradle.parallel=false
org.gradle.caching=true
org.gradle.configuration-cache=false

mod.id=mobreactions
mod.name=Mob Reactions
mod.version=0.10.0
mod.group=io.github.profetgit.mobreactions
mod.author=Profet
mod.description=Mobs react to your hits with bouncy, cartoony animations. Visual only and client-side.
mod.license=All-Rights-Reserved
mod.homepage=https://modrinth.com/user/Profet
